[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "MultiAgentSystem"
version = "0.1.0"
dependencies = [
    "pydantic-ai",
    "pydantic",
    "tavily-python",
]
